config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    devise_for :users
    resources :users, only: %i(index show destroy)
    get "admin_hotels", to: "hotels#admin_index"
    get "admin_hotels/:id", to: "hotels#admin_show"
    resources :hotels
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize user
    can :read, Hotel

    if user.present?
      can :show, User, id: user.id

      if user.has_role? :moderator
        can [:new, :create, :admin_index], Hotel
        can [:admin_show, :edit, :update, :destroy], Hotel,
          id: Hotel.with_role(:moderator, user).pluck(:id)
        can :manage, :all if user.has_role? :admin
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  resourcify
  has_many :hotel_images, dependent: :destroy
  has_many :images, through: :hotel_images, dependent: :destroy
  accepts_nested_attributes_for :hotel_images, allow_destroy: true
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/hotel_image.rb
class HotelImage < ApplicationRecord
  belongs_to :hotel
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  has_one :hotel_image, dependent: :destroy
  has_one :hotel, through: :hotel_image
  mount_uploader :image, ImageUploader
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, through: :users_roles

  belongs_to :resource,
    polymorphic: true,
    optional: true

  validates :resource_type,
    inclusion: {in: Rolify.resource_types},
    allow_nil: true

  scopify
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :room_images, dependent: :destroy
  has_many :images, through: :room_images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/room_image.rb
class RoomImage < ApplicationRecord
  belongs_to :room
  belongs_to :image
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable

  after_create :assign_default_role
  scope :ordered_by_name, ->{order :name}

  def assign_default_role
    self.add_role(:moderator) if self.roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @hotels = kmnr_paginate_record Hotel.all,
      params[:page],
      Settings.max_hotel_per_page
  end

  def admin_index
    if current_user.has_role? :moderator
      @hotels = kmnr_paginate_record Hotel.with_role(:moderator, current_user),
        params[:page], Settings.max_hotel_per_page
    end

    if current_user.has_role? :admin
      @hotels = kmnr_paginate_record Hotel.all,
        params[:page], Settings.max_hotel_per_page
    end
  end

  def new; end

  def create
    @hotel = Hotel.new hotel_params

    if @hotel.save
      flash[:success] = t ".hotel_created"
      current_user.add_role :moderator, @hotel
    else
      flash[:notice] = t ".hotel_created_failed"
    end
    redirect_to new_hotel_url
  end

  def show; end

  def admin_show; end

  def edit; end

  def update
    if @hotel.update hotel_params
      flash[:success] = t ".hotel_updated"
      redirect_to hotels_url
    else
      flash[:notice] = t ".hotel_updated_failed"
      redirect_to edit_hotels_url
    end
  end

  def destroy
    @hotel.destroy
    flash[:success] = t ".hotel_deleted"
    redirect_to hotels_url
  end

  private

  def kmnr_paginate_record record, page, max_page
    Kaminari.paginate_array(record).page(page).per max_page
  end

  def hotel_params
    params.require(:hotel).permit(:name,
      :address, :phone_number,
      :country, :city, :state,
      :website, :price_start, :price_end,
      :luxury, :description,
      images_attributes: [:id, :image, :_destroy])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user, :load_hotel
  before_action :correct_room_hotel, :load_room, except: %i(index new create)

  def index
    @rooms =
      Kaminari
      .paginate_array(@current_hotel.rooms)
      .page(params[:page])
      .per Settings.max_room_per_page
  end

  def new
    @room = Room.new
    @room.images.build
  end

  def show
    @images =
      Kaminari
      .paginate_array(@room.images)
      .page(params[:page])
      .per Settings.max_image_per_page
  end

  def create
    @room = Room.new room_params

    if @room.save
      flash[:info] = t ".room_created"
    else
      flash[:info] = t ".room_created_failed"
    end
    render :new
  end

  def edit; end

  def update
    if @room.update room_params
      flash[:success] = t ".room_updated"
      redirect_to rooms_url
    else
      flash[:notice] = t ".room_updated_failed"
      render :edit
    end
  end

  private

  def room_params
    params.require(:room).permit(:name,
      :hotel_id, :size, :max_persons,
      :facilities, :price, :description,
      images_attributes: [:id, :picture])
  end

  def load_room
    @room = Room.find_by id: params[:id]

    return if @room
    flash[:danger] = t ".room_not_found"
    redirect_to rooms_url
  end

  def load_hotel
    @current_hotel = Hotel.find_by id: params[:hotel_id]

    return if @current_hotel
    flash[:danger] = t ".hotel_not_found"
    redirect_to hotels_url
  end

  def correct_room_hotel
    return if @current_hotel.rooms.find_by id: params[:id]
    flash[:danger] = t ".incorrect_room"
    redirect_to rooms_url
  end
end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController
  def show_results
    render :results
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def room; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.ordered_by_name.page params[:page]
  end

  def show; end

  def destroy
    flash[:success] = t "delete_user" if @user.destroy
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "Tripbricks"
    page_title.blank? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: Settings.gravatar_size
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/hotels/_form.html.erb
<%= form_for @hotel do |f| %>
  <%= render "shared/errors_messages", object: f.object %>

  <%= f.label :name, t(".name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :address, t(".address") %>
  <%= f.text_field :address, class: "form-control" %>

  <%= f.label :phone_number, t(".phone_number") %>
  <%= f.text_field :phone_number, class: "form-control" %>

  <%= f.label :country, t(".country") %>
  <%= f.text_field :country, class: "form-control" %>

  <%= f.label :city, t(".city") %>
  <%= f.text_field :city, class: "form-control" %>

  <%= f.label :state, t(".state") %>
  <%= f.text_field :state, class: "form-control" %>

  <%= f.label :website, t(".website") %>
  <%= f.text_field :website, class: "form-control" %>

  <%= f.label :description, t(".description") %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.label :luxury, t(".luxury") %>
  <%= f.number_field :luxury, class: "form-control" %>

  <%= f.label :price_start, t(".price_start") %>
  <%= f.number_field :price_start, step: :any, class: "form-control" %>

  <%= f.label :price_end, t(".prize_end") %>
  <%= f.number_field :price_end, step: :any, class: "form-control" %>
  
  <div class="form-group" id="file-field">
    <%= f.label :images, class: "col-md-4 control-label"%>
    <div class="col-md-4">
      <table class="user-photo-form">
        <%= f.fields_for :images do |image| %>
          <%= render "image_fields", f: image %>
        <% end %>
        <div class='links'>
          <%= link_to_add_association (t ".add_a_photo"), f, :images, class: "btn btn-default" %>
        </div>
      </table>
    </div>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/hotels/_hotel.html.erb
<div class="hotellist-item">
    <div class="col-xs-12 col-sm-3 no-padding hotellist-picture">
        <%= link_to image_tag("hotel/bluesun_s_hotel.jpg", alt: "hotel", class: "img-responsive"), "#" %>
    </div>
    <div class="col-xs-12 col-sm-9 no-padding hotellist-content">
        <div class="row hotellist-info">
            <div class="col-xs-12 col-sm-8 col-md-9 hotel-name">
                <h3>
                    <%= link_to hotel do %>
                        <%= hotel.name %>
                        &nbsp;&nbsp;
                        <span class="fa fa-star text-yellow"></span>
                        <span class="fa fa-star text-yellow"></span>
                        <span class="fa fa-star text-yellow"></span>
                        <span class="fa fa-star text-yellow"></span>
                        <span class="fa fa-star text-yellow"></span>
                    <% end %>
                </h3>
                <p class="">
                    <%= link_to "#{hotel.city} - Show on map", data: {toggle: "modal", target: "#modalLocation"} do %>
                        <span class="fa fa-map-marker"></span>
                        <span class="fa fa-location-arrow"></span> (2.5 km from center)
                    <% end %>                    
                </p>
            </div>
        </div>
        <div class="row hotellist-desc">
            <div class="col-xs-12 col-sm-8 col-md-9 hotellist-desc-l">
                <p>5 people are looking right now</p>
                <p><a href="#">Reservation possible without a credit card</a></p>
                <p class="label-violet">93% of guest reviewers had their expectations of this property met or exceeded</p>
                <p>Apartment Max people: 2 – Double Room</p>
                <p class="text-violet">Only 1 room left!</p>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-3 hotellist-price">
                <h2 class="text-blue text-right price-ht">USD 
                <span class="text-yellow">
                    <%= hotel.price_start %> - <%= hotel.price_end %>
                </span></h2>
                <%= link_to t(".delete_hotel"), hotel, method: :delete, class: "btn btn-blue btn-select-room" %>
            </div>
        </div>
    </div>
</div>

app/views/hotels/_image_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= f.file_field :image, class: "hotel-image" %>
    <%= f.hidden_field :image_cache, value: f.object.image_cache %>
  </td>
  <td class="preview-image">
    <% if f.object.image.url.present? %>
      <%= image_tag f.object.image.url, height: 100 %>
    <% end %>
  </td>
  <td>
    <%= link_to_remove_association (t "remove"), f %>
  </td>
</tr>

app/views/hotels/admin_index.html.erb
<% provide :title, t("hotels") %>
<h1><%= t "hotels" %></h1>
<%= paginate @hotels %>
<ul class="hotels">
  <%= render @hotels %>
</ul>
<%= paginate @hotels %>

app/views/hotels/admin_show.html.erb
<% provide :title, @hotel.name %>
<div class="container">
  <p>Name: <%= @hotel.name %></p>
</div>

app/views/hotels/edit.html.erb
<% provide :title, t(".edit_hotel") %>
<% provide :button_text, t(".edit_hotel") %>
<h1><%= t ".edit_hotel" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/hotels/index.html.erb
<% provide :title, t("hotels") %>
<h1><%= t "hotels" %></h1>
<%= paginate @hotels %>
<ul class="hotels">
  <%= render @hotels %>
</ul>
<%= paginate @hotels %>

app/views/hotels/new.html.erb
<% provide :title, t(".create_new_hotel") %>
<% provide :button_text, t(".create_new_hotel") %>
<h1><%= t ".create_new_hotel" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/hotels/show.html.erb
<% provide :title, @hotel.name %>
<div class="container">
  <p>Name: <%= @hotel.name %></p>
  <% @images.each do |image| %>
    <%= image_tag image.picture_url %>
  <% end %>
</div>

app/views/layouts/_banner.html.erb
<div class="full-row banner">
    <!-- Carousel head -->
    <div id="carousel-banner-picture" class="carousel slide " data-ride="carousel" data-interval="8000">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <%= link_to image_tag("banner.jpg", alt: "Hoi An", class: "img-responsive banner-img"), "#" %>
                <div class="carousel-caption">
                    <p class="nation-caption"><span><%= t "Viet_Nam" %></span></p>
                    <h1 class="location-caption"><%= t "Hoi_An" %></h1>
                </div>
            </div>
            <div class="item">
                <%= link_to image_tag("banner-2.jpg", alt: "Hoi An", class: "img-responsive banner-img"), "#" %>
                <div class="carousel-caption">
                    <p class="nation-caption"><span><%= t "Viet_Nam" %></span></p>
                    <h1 class="location-caption"><%= t "Ha_Noi" %></h1>
                </div>
            </div>
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-banner-picture" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-banner-picture" data-slide-to="1"></li>
            </ol>
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-banner-picture" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only"></span>
        </a>
        <a class="right carousel-control" href="#carousel-banner-picture" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only"></span>
        </a>
    </div>
    <!-- .Carousel head -->
</div>
<!-- .full row-Banner -->

app/views/layouts/_filter_hotel.html.erb
<div class="col-xs-12 col-sm-3 page-left filter-left-mb__overlay">
    <div class="filter-head__overlay">
        <h3><%= t "Filter" %></h3>
        <span class="fa fa-close filter-head-close__overlay"></span>
    </div>
    <div class="filter-left">
        <div class="filter-head">
            <h3><%= t "Filter_Results" %> <span class="pull-right reset-filter"><%= t "Reset_Filter" %></span></h3>
            <p><%= t "Showing_results" %></p>
        </div>
        <!-- Budget -->
        <filter class="box box-filter-budget">
            <div class="filter-title">
                <p><b><%= t "Your_Budget" %></b></p>
            </div>
            <div class="filter-inner">
                <ul class="list-group">
                    <li class="list-group-item">
                        <label class="text-blue">
                            <input type="checkbox" name="" value="" />
                            <span>VND 0 - VND 1,300,000 <%= t "per_night" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label class="text-blue">
                            <input type="checkbox" name="" value="" />
                            <span>VND 0 - VND 1,300,000 <%= t "per_night" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label class="text-blue">
                            <input type="checkbox" name="" value="" />
                            <span>VND 0 - VND 1,300,000 <%= t "per_night" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label class="text-blue">
                            <input type="checkbox" name="" value="" />
                            <span>VND 0 - VND 1,300,000 <%= t "per_night" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label class="text-blue">
                            <input type="checkbox" name="" value="" />
                            <span>VND 0 - VND 1,300,000 <%= t "per_night" %></span>
                        </label>
                    </li>
                </ul>
            </div>
        </filter>
        <!-- .Budget -->
        <!-- Star rating -->
        <filter class="box" id="accordioncollapseRating">
            <div class="filter-title">
                <p><%= t "Star_Rating" %><span class="fa fa-angle-down pull-right" role="button" data-toggle="collapse" data-parent="#accordioncollapseRating" href="#collapseRating" aria-expanded="true" aria-controls="collapseRating"></span></p>
            </div>
            <div class="filter-inner panel-collapse collapse in" id="collapseRating">
                <ul class="list-group">
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="5star" value="">
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="5star" value="">
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="5star" value="">
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="5star" value="">
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="5star" value="">
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                        </label>
                    </li>
                </ul>
            </div>
        </filter>
        <!-- .Star rating -->
        <!-- Facilites -->
        <filter class="box" id="accordionFacilities">
            <div class="filter-title">
                <p class="text-blue"><%= t "Facilities" %> <span class="fa fa-angle-down pull-right" role="button" data-toggle="collapse" data-parent="#accordionFacilities" href="#collapseFacilities" aria-expanded="true" aria-controls="collapseFacilities"></span></p>
            </div>
            <div class="filter-inner panel-collapse collapse in" id="collapseFacilities">
                <ul class="list-group">
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "WiFi" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Swimming_Pool" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Parking" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Restaurant" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Elevator" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Fitness_Center" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Meeting_Facilities" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Airport_Transfer" %></span>
                        </label>
                    </li>
                </ul>
            </div>
        </filter>
    </div>
    <!-- .Filter left -->
</div>

app/views/layouts/_footer.html.erb
<footer class="full-row footer">
    <div class="container footer-content">
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <%= link_to image_tag("logo.png", alt: "logo", class: "img-responsive img-logo"), "#" %>
                <p><i><%= t "about_tripbricks" %></i></p>

            </div>
            <div class="col-xs-12 col-sm-3">
                <h3 class="text-uppercase"><b>Contact Info</b></h3>
                <p><span class="fa fa-map-marker text-yellow"></span> <%= Settings.address %></p>
                <p><span class="fa fa-phone text-yellow"></span> <%= Settings.telephone %></p>
                <p><span class="fa fa-envelope-o text-yellow"></span> <%= Settings.email_tripbricks %></p>
            </div>
            <div class="col-xs-12 col-sm-3">
                <h3 class="text-uppercase"><b><%= t "Discover" %></b></h3>
                <ul class="list-recent-post">
                    <li>
                        <a href="article.html"><%= t "About_Us" %></a>
                    </li>
                    <li>
                        <a href="article.html"><%= t "Terms and conditions" %></a>
                    </li>
                    <li>
                        <a href="article.html"><%= t "Privacy_policy" %></a>
                    </li>
                    <li>
                        <a href="article.html"><%= t "Q&A" %></a>
                    </li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-3">
                <h3 class="text-uppercase"><b><%= t "Connect_with_us" %></b></h3>
                <ul class="list-inline list-connect-us">
                    <li>
                      <%= link_to image_tag("icon-footer/fb.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/dautotuong" %>
                    </li>
                    <li>
                      <%= link_to image_tag("icon-footer/sp.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/dautotuong" %>
                    </li>
                    <li>
                      <%= link_to image_tag("icon-footer/tw.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/dautotuong" %>
                    </li>
                    <li>
                      <%= link_to image_tag("icon-footer/yt.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/dautotuong" %>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<% if current_page?(root_path) || current_page?("/") %>
  <header class="">
<% else %>
  <header class="black-header">
<% end %>
    <nav class="navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-3">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to image_tag("logo.png", alt: "logo", class: "img-responsive pull-left img-logo logo-web"), root_path %>
            </div>
            <div class="collapse navbar-collapse navbar" id="navbar-collapse-3">
                <ul class="nav navbar-nav navbar-left">
                    <li><%= link_to t("Hotels"), "#" %></li>
                    <li><%= link_to t("Destination"), "#" %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="li-number">
                        <a href="tel:+84 (0) 98 453 0860"><span class="fa fa-phone text-violet"></span><%= Settings.telephone %></a>
                    </li>
                    <li class="header-login-register">
                      <% if user_signed_in? %>
                        <%= link_to t("profile"), current_user %>
                        <%= link_to t("logout"), destroy_user_session_path, method: :delete %>
                      <% else %>
                        <%= link_to t("login"), new_user_session_path %>
                        <%= link_to t("signup"), new_user_registration_path %>
                      <% end %>
                    </li>
                </ul>
                <div class="collapse nav navbar-nav nav-collapse" id="nav-collapse3">
                    <form class="navbar-form navbar-right" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search" />
                        </div>
                        <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                    </form>
                </div>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/rooms/edit.html.erb
<% provide :title, t(".edit_room_info") %>
<% provide :button_text, t(".edit_room_info") %>
<h1><%= t ".edit_room_info" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/rooms/index.html.erb
<% provide :title, t(".hotel_rooms") %>
<h1><%= t "Rooms" %></h1>
<%= paginate @rooms %>
<div class="col-xs-12 no-padding result-slht-table">
    <table class="table table-bordered table-responsive slht-table">
        <thead>
            <th><%= t "Guests" %></th>
            <th><%= t "Room_Types" %></th>
            <th><%= t "Price_per_night" %></th>
            <th class="slht-th-choices"><%= t "Facilities" %></th>
        </thead>
        <%= render @rooms %>
    </table>
</div>
<%= paginate @rooms %>

app/views/users/shared/_form.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label t("name"), class: "form-text" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label t("email"), class: "form-text" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label t("password"), class: "form-text" %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> <%= t "characters_minimum" %>)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label t("password_confirmation"), class: "form-text" %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit t("sign_up"), class: "btn btn-primary" %>
  </div>
<% end %>

<%= render "users/shared/links" %>

app/views/users/shared/_links.html.erb
<%- if controller_name != "sessions" %>
  <%= link_to t("log_in"), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != "registrations" %>
  <%= link_to t("sign_up"), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != "passwords" && controller_name != "registrations" %>
  <%= link_to t("forget_pass"), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != "confirmations" %>
  <%= link_to t("didnt_receive_mail"), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "#{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>